### ISSUE TITLE
Unable to render a subset of materialization config forms.

### ISSUE THREAD

**Issue by kiahna-tucker** [estuary/ui#107]
Currently, the following materialization endpoint and resource configuration schemas cannot be rendered: PostgreSQL, BigQuery, and Snowflake.

### Notes

When evaluating the issue, I noticed a pattern amongst the schemas whose refs were able to be resolved: the `$ref` property was present. When a schema containing a defined `$ref` is passed to `JsonRefs.resolveRefs()`, the `$schema` property in the original schema is placed in the object of the `refs` property in the resulting schema.

For example, consider the following sample schema:

```ts
{
  "$ref": "#/definitions/Config",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": { ... }
  // additional properties
}
```

For the purpose of this example, let's refer to it as _Origin Schema A_. When _Origin Schema A_ is passed to `JsonRefs.resolveRefs()`, it creates _Resolved Schema A_ that **can** be rendered and is defined as follows:

```ts
{
  "refs": {
    "#": {
      "def": {
        "$ref": "#/definitions/Config",
        "$schema": "http://json-schema.org/draft-04/schema#",
        "definitions": { ... },
        },
        // additional properties
      },
    // additional property
  },
  "resolved": {
    "type": "object",
    "required": ["database", "host", "password", "port", "user"],
    // additional properties
}
```

Now, say there is an _Origin Schema B_ that is defined as follows:

```ts
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "required": ["host", "password", "user"],
  // additional properties
```

When _Origin Schema B_ is passed to `JsonRefs.resolveRefs()`, it creates _Resolved Schema B_ that **cannot** be rendered and is defined as follows:

```ts
{
  "refs": {},
  "resolved": {
    "type": "object",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "required": ["host", "password", "user"],
    // additional properties
   },
```

I am curious if the presence of the `$schema` property in the resolved schema (see _Resolved Schema B_ reference) causes the schema validation error. Sharing this context in the event it helps find a path to a solution.

### Reference
<img width="1920" alt="app__materialization-create-error__postgres__no-schema-with-key-or-ref" src="https://user-images.githubusercontent.com/77648584/166502995-c1e33e7d-d99c-4652-b25a-afe57c6a2988.PNG">

**Comment by psFried** [comment]
The resolution here involved relaxing the `Ajv` instance that's used behind the scenes of JSON forms for validation and to populate default values. This was done for two different reasons:
- To allow us to use a single Ajv instance for both draft-4 and draft-7+ schemas
- To be a little more forgiving of subtly non-compliant schemas, since those seem to be so common in the wild

Ultimately, it stinks a bit to handle schemas in this way. A better approach, suggested by @jgraettinger, would be to transform schemas on the backend into a format that's easier to deal with for the UI (e.g. a strictly compliant draft-20 schema). If we do that, then we can un-relax the `Ajv` instance.
