### ISSUE TITLE
ui: Build out local UI state management for collecting change sets prior to calling a build endpoint

### ISSUE THREAD

**Issue by kiahna-tucker** [estuary/ui#21]
Define a global state for change set-related information within the UI.

Overarching state management discussions can be found in the [parent issue](https://github.com/estuary/ui/issues/3).

**Comment by kiahna-tucker** [comment]
# Preliminary Design Ideas & Considerations
Last Updated: Feb. 17, 2022
<hr>

This segment of overall application state must have a well-defined and predictable internal structure (i.e., the content being stored) while its external structure (i.e. the _path_ to the stored content) needs to scale with a considerable degree of flexibility. Catalog namespaces mirror that of a file system, which has its advantages and disadvantages when defining state that will be investigated, in part, below. Momentarily disregarding the alluded nuance, the file system-based namespace leads me to believe the change set state could leverage the **dictionary data structure**. Since a single user can have access to numerous catalogs, each tied to a variety of accounts, the UI will need to traverse the change set state with ease when fetching or storing data. A dictionary inherently supports multi-tiered data and allows for speedy lookup, therefore the data structure is worth consideration and will be the primary focus of this discussion.

<br />

## Implementation
While a file system-based namespace is the identifier for a resource, I would like to avoid replicating the file system in the UI state (as it pertains to nesting). Any opportunity to make a level of the state shallow should be taken advantage of, but a strategic approach to flattening is recommended*.

**NOTE:** The resource objects in the code samples below are purely illustrative. Further discussion is required to devise compelling interface design suggestions.

### **Key Strategies**
#### _Strategy One - Primary Key Only_

A single, primary key corresponding to the namespace to which the resource belongs would be used to index the state.

**Considerations:**

* In the event the endpoint accepting the resource requires the passing of its namespace as a single string, one-to-one mapping between namespace and resource requires no data transformation to create that request payload.

* Single type definition for the contents of the state.

* The entire namespace to which a resource belongs must be known in order to index the state.

* Resources are only grouped if they belong to the same namespace.

<br />

```ts
// Change Set State - Captures
{
    ['acmeCo/anvilMaker'] : [
        {
            namespace: 'acmeCo/anvilMaker/myFirstCapture',
            resource: 'myFirstCapture',
            schema: // some JSON object
        },
        {
            namespace: 'acmeCo/anvilMaker/mySecondCapture',
            resource: 'mySecondCapture',
            schema: // some JSON object
        }
    ],
    ['acmeCo/materials/ironSupplier']: [
        {
            namespace: 'acmeCo/materials/ironSupplier/myFirstCapture',
            resource: 'myFirstCapture',
            schema: // some JSON object
        },
    ],
}
```

<br />

#### _Strategy Two - Primary and Secondary Keys_

A primary key corresponding to a higher level segment of the namespace to which the resource belongs would be used to index the state's outer dictionary. A secondary key corresponding to the remainder of the namespace to which a resource belongs would be used to index the state's inner dictionary.

**Considerations:**

* Creates an opportunity to predefine the outer dictionary's keyspace before becoming aware of the inner dictionary's keyset. This allows the UI to do primitive namespace validation without the need of a service.

* Compound slices of state can be fetched with a single query.

* Two dictionary layers and an array must be indexed to fetch a single resource.

* Two type definitions are required for the contents of the state.

<br />

```ts
// Change Set State - Captures
{
    ['acmeCo'] : {
        ['anvilMaker'] : [
            {
                namespace: 'acmeCo/anvilMaker/myFirstCapture',
                resource: 'myFirstCapture',
                schema: // some JSON object
            },
            {
                namespace: 'acmeCo/anvilMaker/mySecondCapture',
                resource: 'mySecondCapture',
                schema: // some JSON object
            }
        ],
        ['materials/ironSupplier']: [
            {
                namespace: 'acmeCo/materials/ironSupplier/myFirstCapture',
                resource: 'myFirstCapture',
                schema: // some JSON object
            },
        ],
    }
}
```

<br />

### **State Segmentation Strategies**
#### _Strategy One - Single State_

A single change set state will be defined for the entire application.

**Considerations:**

* A slice of state will contain all the resource information within a particular namespace, regardless of type.

* To fetch (or evaluate the existence of) a subset of resource types for a namespace, the UI would need to iterate over the entirety of the dictionary entry and filter its contents accordingly.

* To fetch (or evaluate the existence of) a subset of resource types in the change set at large, the UI would need to iterate over the entirety of each dictionary entry and filter its contents accordingly.

* If the resource details that need to be stored varies based upon resource type, the dictionary type may need to involve generics to achieve the highest degree of type-safety.

<br />

```ts
// Change Set State
{
    ['acmeCo/anvilMaker'] : [
        {
            resource: 'myFirstCapture',
            resourceType: 'capture',
            schema: // some JSON object
        },
        {
            resource: 'mySecondCapture',
            resourceType: 'capture',
            schema: // some JSON object
        },
        {
            resource: 'myFirstMaterialization',
            resourceType: 'materialization',
            schema: // some JSON object
        },
    ],
    ['acmeCo/materials/ironSupplier']: [
        {
            resource: 'myFirstCapture',
            resourceType: 'capture',
            schema: // some JSON object
        },
        {
            resource: 'myFirstMaterialization',
            resourceType: 'materialization',
            schema: // some JSON object
        },
        {
            resource: 'mySecondMaterialization',
            resourceType: 'materialization',
            schema: // some JSON object
        }
    ],
    ['acmeCo/tools/chiselDesigner'] : [
        {
            resource: 'myFirstMaterialization',
            resourceType: 'materialization',
            schema: // some JSON object
        },
    ],
}
```

<br />

#### _Strategy Two - Independent State for Each Resource Type_

A change set state will be defined for each resource type (i.e., capture, materialization, derivation, etc.).

**Considerations:**

* Simplicity of resource type queries.

* The size of the overall change set state is flexible.

* Single type definition is required for the contents of the state.

<br />

```ts
// Change Set State - Captures
{
    ['acmeCo/anvilMaker'] : [
        {
            namespace: 'acmeCo/anvilMaker/myFirstCapture',
            resource: 'myFirstCapture',
            schema: // some JSON object
        },
        {
            namespace: 'acmeCo/anvilMaker/mySecondCapture',
            resource: 'mySecondCapture',
            schema: // some JSON object
        }
    ],
    ['acmeCo/materials/ironSupplier']: [
        {
            namespace: 'acmeCo/materials/ironSupplier/myFirstCapture',
            resource: 'myFirstCapture',
            schema: // some JSON object
        },
    ],
}

// Change Set State - Materializations
{
    ['acmeCo/anvilMaker'] : [
        {
            resource: 'myFirstMaterialization',
            schema: // some JSON object
        },
    ],
    ['acmeCo/materials/ironSupplier']: [
        {
            resource: 'myFirstMaterialization',
            schema: // some JSON object
        },
        {
            resource: 'mySecondMaterialization',
            schema: // some JSON object
        }
    ],
    ['acmeCo/tools/chiselDesigner'] : [
        {
            resource: 'myFirstMaterialization',
            schema: // some JSON object
        },
    ],
}
```

<br />

*A future feature that may be worthwhile would be to allow users to filter the resources listed in their change set. For example, if one wanted to view all resources within `acmeCo/materials/ironSupplier` in the set. This feature may be challenging to accomplish if a namespace can have infinite depth depending upon how the state is structured. Further thought, research, and discussion is required.

<br />

## Questions
Some of the questions in this section may fall out of the scope of Q1 and, potentially, the foreseeable future.

* In what ways will the change set state design need to scale in the near future? Are there any features that could influence the design choices made at this stage (e.g., resource filtering, automated resource pruning, etc.)?

* How will a service relay the namespace of a resource to the UI? What form will the namespace take (i.e., single or segmented string)? Can a namespace be decomposed into meaningful segments? If so, what would each segment represent? As the definition of and interactions with namespaces evolve over time, it may be worthwhile to maintain a visual that identifies the aspects of a namespace.

* Are resources differentiated by type? In other words, can multiple resources of a unique type within the same namespace have the same name? For example, can a derivation named _anvils_ and a capture named _anvils_ exist within `acmeCo/products`? If not (and I imagine this is not possible), at what point would this error be caught? What entity will catch this error (i.e., UI or a service)? How will this scenario be handled from a UX perspective?

* How should the presence of a duplicate resource in the change set be handled from a UX perspective?

* What aspects of a resource need to be captured? What subset of that information is required to kick off a build? What subset of that information would be useful to present in the UI? The _Builds - 2_ frame in the sample Figma mockup provides a starting point for defining the change set view in the UI.

* What terminology will be used in general (e.g., does a change set contain _resources_ or _entities_?, etc.) as well as those unique to the representation of a change set in the UI (e.g., what is the name of the change set's view on the build page? Is it a _change set table_ or a _change set list_ or a _change set card_ that contains a _table_ or _list_ or a _change set section_ that contains a _table_ or _list_?, etc.)? This is tied to the question directly above. It may be worth keeping a running glossary in this GitHub issue. Eventually, independent glossaries will need to be consolidated. Thus, it may be worthwhile for each repository to apply the same label to an issue where a glossary is being maintained.

* How should permission/access revocations be handled from a UX perspective? For example, a user created a resource, added it to the change set, then had their permissions revoked to generate and/or view that resource, would this prompt any consequent changes? Will that user no longer be able to see that resource in the change set? For users that do have permission/access view and/or interact with that resource, will it be flagged in any way since it was created by someone whose permission/access was revoked? Will this flag be visual (e.g., change in background color, explicit flag icon placed in a _notifications_ column of the change set table view in the UI that can be opened to present a message stating suggested next steps, etc.), functional (e.g., preventing builds and activations of this resource), or a combination of the two? If the entry in the change set will be flagged by the UI, will different flagging methods be employed depending on the permission/access a user has (e.g., users with basic permission/access to the resource will be unable to build the resource and see a visual flag while a user with a higher level of permission/access will only encounter the visual flag)?

**Comment by psFried** [comment]
Great writeup. It's good to see how you're thinking about state management. I can give straight forward answers to at least some of the questions, but I'll start with just a general summary of the "why", to make sure we're on the same page.

The state management that we need right now is necessary because the end-to-end process of creating a task is quite complex, and we need to bridge the gap between that complexity and the very simple HTTP endpoint that we're envisioning. To create a capture requires the creation of a sops-encrypted endpoint configuration, one or more JSON schemas (which may reference each other), one or more collections, which reference the schemas, and finally a capture that references both the collection(s) and the endpoint configuration. The HTTP API that we're currently envisioning for this will accept one giant payload that will include _all_ of those things, which means we need somewhere for schemas, collections, and endpoint configurations to live until we're ready to pass them all to the `/build` endpoint. We're using this very simple HTTP endpoint primarily because it seems like the most expedient way to get an MVP. I'm by no means convinced that this is way it should be long term, though, as things will surely start to look at little differently once we have a working MVP.

> In what ways will the change set state design need to scale in the near future?

Big fat question mark, here. I don't even know whether we'll need this kind of state management at all in the future (I also don't know that we _won't_ need it).

> How will a service relay the namespace of a entity to the UI?

First thing is to clarify that "entity" here can mean specifically either a Flow task (`capture`, `derivation`, or `materialization`) or a `collection`. Schemas and endpoint configurations are not currently Flow entities. Each entity has a `name`, for example `acmeCo/products/anvils`, and the name is always communicated as a single string with forward slashes separating the components. This name is hierarchical, and the hierarchy will be used extensively by the authorization system to grant access to things by prefix. Every name must have at least two path components (you can't name something just `acmeCo`) and no entity is allowed to have a name that is a prefix of another (you can't have `acmeCo/products` and `acmeCo/products/anvils`). The first path component is the tenant name, which represents a specific user or organization that is the "owner" of all entities with that prefix.

When we talk about the "namespace", it usually refers to the set of all possible names with a given (possibly empty) prefix. For example, the `acmeCo` namespace refers to the set of all possible names within the `acmeCo` tenant (because they share a prefix). The "global" namespace is the set of all possible names in the system (with an empty `""` prefix). This is conceptually important because the design of the authorization system should allow for any valid prefix to behave just like any other in terms of being a namespace that can hold all entity types (including authz-related entities, once we get there).

> Are entities differentiated by type? In other words, can multiple entities of a unique type within the same namespace have the same name?

![well yes, but actually no](https://i.kym-cdn.com/entries/icons/mobile/000/028/596/dsmGaKWMeHXe9QuJtq_ys30PNfTGnMsRuHuo_MUzGCg.jpg)

Generally, two different entities cannot have the same name, even if they are of different types. The exception to this is that a `derivation` will always have the same name as its corresponding `collection`. This came from the initial conception of a `derivation` as a type of collection. The error would be caught when you submit the build, though we still haven't determined exactly what that will look like. One possibility would be that the `/build` endpoint just returns all errors in the response body.

> What aspects of a entity need to be captured?

I'm not really sure how to answer this, except by pointing you to the [flow JSON schema](https://github.com/estuary/flow/blob/master/flow.schema.json) to see which specific fields are optional or required. I'd be happy to give you a tour, if that would be helpful.

**Comment by kiahna-tucker** [comment]
# Design Direction
Last Updated: Feb. 24, 2022
<hr>

To show proof of concept, the change set state will be initially defined as follows:

* The change set state will be composed of a series of _core slices_, each corresponding to an entity type that can be present within a change set. In other words, each entity type will have its own state that will be maintained independently.

* Every state can be broken into two core segments: a dictionary of all the change set elements with a given entity type and a base suite of operations (i.e., add, remove, and select). The key used to index the aforementioned dictionary will be the prefix of the namespace to which an entity belongs; the dictionary entry will consist of an array of suitable change set elements.

The progression of development will enable the creation of supplementary documentation to help illustrate the active approach as well as refine it.

**NOTE:** [Zustand](https://github.com/pmndrs/zustand) is (currently) the state management library of choice. A separate comment in this thread will outline the logic behind that decision.

**Comment by kiahna-tucker** [comment]
Upon further conversation, this issue can be considered closed as of March 2, 2022.
