### ISSUE TITLE
Next Button Continually Reappears in User Session

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#480]
**Bug**
In [this session](https://app.logrocket.com/tue20y/estuarytest/s/5-1d6b9126-16c8-4ab0-98e4-1cf684f76d6f/0?t=1676012787440.6765) — at around 33 minutes the user clicked next and it wouldn’t advance to save the materialization.  

There was no error message associated and at minimum we should display an error.

**Comment by kiahna-tucker** [comment]
I do not think this _warrants_ an issue, but we should keep an eye out for any replication. Of the user's three attempts to advance the form, the first and third draft IDs are stored (in the UI) because the Test and Save and Publish buttons as well as the specification editor display briefly. My hunch is that something prompted the draft ID in the UI store to be reset. But without insight into the store state in this session and my inability to reproduce this behavior, it is going to be challenging to diagnose.

**Comment by kiahna-tucker** [comment]
The root of this defect lies within the resource config store, more specifically how the resource config object within the store is initialized when a materialize CTA serves as the entry point to the materialization create workflow.

### Recreation Steps:

1. Configure a capture that has at least two bindings.

1. Click the _Save and Publish_ CTA to publish the capture.

1. Click the _Materialize Collections_ CTA to transition to the materialization create workflow.

1. Select the destination for the materialization, preferably one with a resource schema whose required fields are automatically prefilled (e.g., Google Sheets).

1. Configure the materialization by entering information into the **Details** and **Endpoint Configuration** sections of the form. Do not make any alterations to the Output Collections section of the form.

1. Click the _Next_ CTA then observe that the _Test_ and _Save and Publish_ CTAs appear briefly before ultimately being replaced by the _Next_ CTA again.

**NOTE:** This behavior can be observed when the _Materialize_ CTA on the captures table is used to materialize the collections bound to a capture meeting the criteria outlined above.
