### ISSUE TITLE
Select collections to transform directly from the table on the collections page

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#770]
**Bug**
If you select collections and then select the "New Transformation +" button in the UI, your collections won't make their way to the next screen.

**Comment by dyaffe** [comment]
Makes sense that it's a feature request @kiahna-tucker -- in that case, I would suggest that for consistency all grids should work this way.  Multi-selecting checkboxes and then clicking an action button above the grids should start with those entities selected.

**Comment by kiahna-tucker** [comment]
For clarity, all of the entity tables _do_ work this way. The toolbar directly above each table contains available interactions a user can have with its contents; the secondary (i.e., outlined) buttons identify actions you can take on selected rows and the search bar allows you to filter the contents of the table.

The collections table is an interesting case because the derivation create workflow (entered via the primary, _New Transformation_ button) can make use of its data. Nevertheless, there is value to having a primary (i.e., solid, color-filled) button on each page that allows you to enter the relevant creation workflow completely anew that is separate from the table toolbar. I want to state this distinction for the record.

But yes, we can add a _Derive_ or _Transform_ button to the collections table toolbar on the _Collections_ page.
